# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='post',
            name='bu_field',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='current_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='current_year',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='invoice_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='month_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='po_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='probability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='probability_month_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='project_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='project_manager',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='q1_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='q2_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='q3_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='q4_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sow_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sow_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sow_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sow_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sow_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='total_value_of_year',
            field=models.IntegerField(null=True),
        ),
    ]
